bjerkio/website

package.json
web/gatsby-config.js
web/package.json
web/yarn.lock
yarn.lock

- remove sneaky package
- feat: add service worker

add serviceworker

---

.eslintrc
package.json
web/package.json
web/src/components/container.tsx
web/src/components/layouts/components/footer.tsx
web/src/components/layouts/components/header.tsx
web/src/components/layouts/components/logo.tsx
web/src/components/layouts/index.tsx
web/src/components/list/index.ts
web/src/components/list/list-item.tsx
web/src/components/list/list.tsx
web/src/generated/graphql-types.ts
web/src/pages/index.tsx
web/tsconfig.json
yarn.lock

- Added list components
- Fix components with lint
- Fixed eslint errors

fix: fixed bugs with colors in header and footer

---

web/src/components/services-page/service-list-item.tsx
web/src/components/services-page/service-list.tsx
web/src/pages/services.tsx
yarn.lock

**For working this branch need PR #46 to be merged**
Close #38

fix(services): added services page component

---

web/package.json
web/src/components/container.tsx
web/src/components/layouts/components/footer.tsx
web/src/components/layouts/components/header/header.tsx
web/src/components/layouts/components/header/mobile-menu.tsx
web/src/components/layouts/components/header/navbar-mobile.tsx
web/src/components/layouts/components/header/navbar.tsx
web/src/components/layouts/components/logo.tsx
web/src/components/layouts/index.tsx
web/src/generated/graphql-types.ts
yarn.lock

Fixed getting window path
Fixed logo color styling
Close #44

Feat: add mobile menu

---

package.json
web/src/assets/map.svg
web/src/components/contact/employee-list-item.tsx
web/src/components/contact/exployee-list.tsx
web/src/pages/contact.tsx

Feat: add contact page

---

web/src/components/about-page/about-list-item.tsx
web/src/components/about-page/about-list.tsx
web/src/components/layouts/components/header/navbar.tsx
web/src/gatsby-plugin-theme-ui/index.ts
web/src/generated/graphql-types.ts
web/src/pages/about.tsx
web/src/pages/contact.tsx
web/src/pages/services.tsx

Added initial about page without images
Fixed heading width on small screens
Close #52

Feat: about page

---

web/src/components/button.tsx

Modified styles for arrow button animation
Close #64

Feat: Button with arrow needs adjustment

---

web/src/components/container.tsx
web/src/components/layouts/components/contact-footer/contact-footer.tsx
web/src/components/layouts/components/footer/footer.tsx
web/src/components/layouts/index.tsx

- Added contact footer component
- Modified footer margin
Close #73

Feat: Contact footer component

---

web/src/components/layouts/components/header/navbar.tsx

- Modified navbar styles
Close #71

Fix: Navigation bar shrinks when scrolling

---

web/src/components/home-page/call-to-action-box.tsx
web/src/pages/index.tsx

Added additional margin for first SVG
Close #68 #69 #89

fix: Illustration alignment

---

web/src/components/layouts/components/contact-footer/contact-footer.tsx
web/src/components/layouts/components/header/navbar.tsx

fix: Site margins

---

web/src/components/layouts/components/footer/footer.tsx
web/src/pages/contact.tsx

feat: Address update

---

web/src/components/layouts/components/header/navbar.tsx

fix: Temporarily remove language selector

---

web/src/data/en/employees/brage-sekse-aarset.mdx

fix filename of `brage-image.png` to correctly load image.

fix image filename

---

src/components/contact/employee-heading.tsx
src/components/contact/exployee-list.tsx

Adds green duotone to employee pictures.

feat: Add duotone to employee list

---

.github/workflows/push.yml
src/components/contact/employee-heading.tsx
src/components/layouts/components/header/header-note.tsx

- chore: Remove axe and pa11y
- fix: SEO issues

Accessibility fixes

---

.github/dependabot.yml
.github/workflows/push.yml

- chore: Remove axe and pa11y
- chore: Upgrade to new dependabot

chore: Upgrade to new dependabot

---

src/gatsby-plugin-theme-ui/index.js

Add css to Theme-UI root theme

fix: Cursor not pointer when hovering over button

---

.github/workflows/pull-request.yml
.github/workflows/push.yml

fix: Sitemap not found during build

---

package.json
yarn.lock

This PR was created by the Combine PRs action by combining the following PRs:
* #255 chore(deps): bump @theme-ui/prism from 0.9.1 to 0.10.0
* #254 chore(deps): bump gatsby-source-filesystem from 3.8.0 to 3.9.0
closes #255
closes #254

Update combined dependencies

---

src/components/booking.tsx
src/components/layout/footer/footer.tsx

feat: add booking button to footer

---

src/components/layout/header.tsx
src/theme.tsx

Apparently we don't want these?

fix: remove nav links

---

src/components/about/contact-person.tsx

fix: use overflow: hidden to round corners of images

---

src/components/about/contact-person.tsx
src/components/container-with-background.tsx
src/pages/about.tsx
src/pages/index.tsx
src/pages/principles.tsx

feat: place the graphical elements correctly at the side of the page

---

public/cross.svg
src/components/booking.tsx
src/components/container-with-background.tsx
src/components/layout/footer/footer.tsx
src/components/layout/header.tsx
src/components/layout/header/cross.tsx
src/components/layout/header/hamburger.tsx
src/pages/about.tsx
src/pages/index.tsx
src/pages/principles.tsx
src/theme.tsx

The hamburger menu is for the moment only an iconbutton that has no functionality.

 feat: compatibility with mobile device and hamburger menu for accessibility

---

src/components/layout/footer/footer.tsx
src/theme.tsx

* fix: update footer font size and color

fix: updated footer font size and color

---

src/components/layout/header.tsx

Purpose of this PR: Fixing this error aswell as issue #423

Hamburger and cross are not on the same place when clicked

---

src/pages/about.tsx

chore: socials update

---

src/components/about/contact-person.tsx

* fix: scalability on images
* fix: shrinks the images with the screen size

fix: scalability on images

---

src/routes/(default)/terms/+page.svelte

feat: terms page

---

src/routes/stories/esso/story.js
src/routes/stories/gummibaat/+page.svelte
src/routes/stories/gummibaat/story.js
src/routes/stories/hakkespett/+page.svelte
src/routes/stories/hakkespett/story.js
src/routes/stories/storyheader.svelte
src/routes/stories/storytime.svelte
src/routes/stories/tur-paa-stien/+page.svelte
src/routes/stories/tur-paa-stien/story.js
src/routes/stories/water-pipe/+page.svelte
src/routes/stories/water-pipe/story.js

- feat: add stories
- update names

feat: add stories

---

src/routes/events/frokost/+page.svelte

feat: add breakfast event page

---

src/content/event/2023-11-30/frokost.md

Added url to google forms for breakfast event

Added url to events

---

src/content/event/2023-11-30/frokost.md

Updated event

---

astro.config.mjs
biome.json
package.json
pnpm-lock.yaml
src/__tests__/utils.test.ts
src/layouts/json-ld.ts
src/utils.ts

Prettier can be removed once support for HTML, CSS and Markdown is ready. This is a smooth transition.
Read more: https://biomejs.dev/

feat: use biome for lint and format

---

src/content/people/oda-h-wilhelmsen.json

fix: update position of Oda

---

.firebaserc
.github/workflows/on-pull-request.yml
.github/workflows/on-push-dev.yml
.github/workflows/on-push-to-next.yml
firebase.json

Creates a workflow that pushes to staging environments

chore: add workflow to deploy staging website

---

src/components/footer.astro

Adding logo and changing the content.

Restyle of footer

---

src/pages/index.astro

Changed text on the front page

Changed text front page

---

src/pages/artikler/index.astro

This adds a paragraph text header for the articles page 
added a new paragraph with some text introducing articles
This paragraph helps give a vibe about what the articles are about

feat: add header text for articles

---

src/pages/om/index.md

Draft reason: full texts are not ready yet

refactor: update about page

---

src/components/contact-form.astro

This change implements a method for the email address and description to be added to our fresh system
* A script created from fresh has been added to head
* The "text" field has been renamed "description"
This change makes it so when someone fills out a form with their email and what they want help with, we can find the customer and why they reached us. Currently this form sends nothing and the request goes to the void

feat: connect form with crm
